name: Call me

on:
  workflow_dispatch:
    inputs:
      foo:
        description: An input
        required: false
        type: string
        default: hahaheehee
      default-true:
        description: A boolean input (default true)
        required: false
        type: boolean
        default: true
      default-false:
        description: A boolean input (default false)
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      foo:
        description: An input
        required: false
        type: string
        default: hoohooheehee
      default-true:
        description: A boolean input (default true)
        required: false
        type: boolean
        default: true
      default-false:
        description: A boolean input (default false)
        required: false
        type: boolean
        default: false

jobs:
  call:
    name: Call me
    runs-on: ubuntu-latest

    steps:
      - name: Github
        run: echo '${{ toJSON(github) }}'

      - name: Github Event
        run: echo '${{ toJSON(github.event) }}'

      - name: Inputs
        run: echo '${{ toJSON(inputs) }}'
