name: CICD

on:
  workflow_dispatch:
    inputs:
      foo:
        description: An input
        required: false
        type: string
        default: hahaheehee
      default-true:
        description: A boolean input (default true)
        required: false
        type: boolean
        default: true
      default-false:
        description: A boolean input (default false)
        required: false
        type: boolean
        default: false
  push:
    branches:
      - master
    tags:
      - "v*"
    paths:
      - "**"
      - "!docs/**" # Ignore changes in the docs folder
      - "!**.md" # Ignore changes to any markdown file
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "**"
      - "!docs/**" # Ignore changes in the docs folder
      - "!**.md" # Ignore changes to any markdown file
  release:
    types:
      - published
      - released

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    # Skip workflow for releases that are neither pre-release nor latest
    if: >-
      github.event_name != 'release' ||
      github.event.release.prerelease == true ||
      github.event.action == 'released' ||
      (github.event.action == 'published' && github.event.release.prerelease == false)

    steps:
      - run: env
        shell: bash

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: echo "I ran"

      - uses: ./.github/actions/cool

      - name: Github
        run: echo '${{ toJSON(github) }}'

      - name: Github Event
        run: echo '${{ toJSON(github.event) }}'

      - name: Inputs
        run: echo '${{ toJSON(inputs) }}'

  cast:
    name: Cast booleans
    runs-on: ubuntu-latest

    # Skip workflow for releases that are neither pre-release nor latest
    if: >-
      github.event_name != 'release' ||
      github.event.release.prerelease == true ||
      github.event.action == 'released' ||
      (github.event.action == 'published' && github.event.release.prerelease == false)

    outputs:
      default-true: ${{ steps.cast.outputs.default-true }}
      default-false: ${{ steps.cast.outputs.default-false }}

    steps:
      - name: Cast booleans
        id: cast
        run: |
          echo "default-true=${DEFAULT_TRUE}" >> $GITHUB_OUTPUT
          echo "default-false=${DEFAULT_FALSE}" >> $GITHUB_OUTPUT
        env:
          DEFAULT_TRUE: ${{ github.event.inputs.default-true || 'true' }}
          DEFAULT_FALSE: ${{ github.event.inputs.default-false || 'false' }}

  call:
    name: Call me
    uses: ./.github/workflows/call.yml
    needs: cast
    with:
      foo: ${{ github.event.inputs.foo || 'foo' }}
      # Must be Boolean
      default-true: ${{ needs.cast.outputs.default-true == 'true' }}
      # Must be Boolean
      default-false: ${{ needs.cast.outputs.default-false == 'true' }}
