name: CICD

on:
  workflow_dispatch:
    inputs:
      foo:
        description: An input
        required: false
        type: string
        default: hahaheehee
      default-true:
        description: A boolean input (default true)
        required: false
        type: boolean
        default: true
      default-false:
        description: A boolean input (default false)
        required: false
        type: boolean
        default: false
  push:
    branches:
      - master
    tags:
      - "v*"
    paths:
      - "**"
      - "!docs/**" # Ignore changes in the docs folder
      - "!**.md" # Ignore changes to any markdown file
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "**"
      - "!docs/**" # Ignore changes in the docs folder
      - "!**.md" # Ignore changes to any markdown file
  release:
    types: [published]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: echo "I ran"

      - uses: ./.github/actions/cool

      - name: Github
        run: echo '${{ toJSON(github) }}'

      - name: Github Event
        run: echo '${{ toJSON(github.event) }}'

      - name: Inputs
        run: echo '${{ toJSON(inputs) }}'

  call:
    name: Call me
    uses: ./.github/workflows/call.yml
    with:
      foo: ${{ github.event.inputs.foo || 'foo' }}
      default-true: ${{ github.event.inputs.default-true == 'true' || true }}
      default-false: ${{ github.event.inputs.default-false == 'true' || false }}
